title: Alessandro Aere
author: GitHub User
email: alessandro.aere@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Scientific blog about data science, machine learning, artificial intelligence,
  statistics, deep learning and neural networks.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Alessandro Aere
  tagline: Statistician. Data Scientist. AI Analyst.
  date_format: "%b %-d, %Y"
  style: green
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  alessandroaere
    linkedIn: in/alessandro-aere-b7b710130
    rss: rss


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

theme: texture
remote_theme: thelehhman/texture
plugins:
  - jekyll-seo-tag
#  - jekyll-feed
